blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts import views as post_home



urlpatterns = [
    path('admin/', admin.site.urls),
    path("posts/", include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path, include
# from posts import views as post_home
from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete
)

app_name="posts"


urlpatterns = [
    path('', post_list, name="home"),
    path("create/", post_create),
    path("detail/<id>/", post_detail, name="detail"),
    path("update/<id>/", post_update, name="update"),
    path("delete/<id>/", post_delete),
]

posts/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.db.models.signals import pre_save

from django.utils.text import slugify

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1,on_delete=models.CASCADE)
    title = models.CharField(max_length=40)
    # slug = models.SlugField(unique=True)
    image = models.ImageField(null=True, blank=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True) # will be set only one time

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"id": self.id})

    def get_update_url(self):
        return reverse("posts:update", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp", "-updated"]

# def create_slug(instance, new_slug=None):
#     slug = slugify(instance.title)
#     if new_slug is not None:
#         slug = new_slug
#     qs = Post.objects.filter(slug=slug).order_by("-id")
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" %(slug, qs.first().id)
#         return create_slug(instance, new_slug=new_slug)
#     return slug


# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     slug = slugify(instance.title)
#     qs = Post.objects.filter(slug=slug)
#     exists = qs.exists()
#     if exists:
#         slug = "%s-%s" %(slug, qs.first().id)
#     instance.slug = slug
    # if not instance.slug:
    #     instance.slug = create_slug(instance)

# pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'image',
            'content',
        ]

posts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404

from .models import Post
from .forms import PostForm

from django.core.paginator import Paginator
from django.shortcuts import render

from django.db.models import Q #For search - Q lookup

# from myapp.models import Contact

# Create your views here.
# request.build_absolute_uri
def post_list(request):
    queryset_list = Post.objects.all() #.order_by("-timestamp")

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__username__icontains=query) 
            ).distinct()

    paginator = Paginator(queryset_list, 9) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    queryset = paginator.get_page(page_number)

    context = {
        "object_list": queryset,
        "title": "list"
    }
    return render(request, "post_list.html", context)

def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    print(form)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        print(instance.get_absolute_url())
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    # else:
    #     messages.success(request, "Not Successfully Created")
    context  ={
        "form": form
    }
    return render(request, "post_form.html", context)

def post_detail(request, id=None):
    print(id)
    queryset = get_object_or_404(Post, id=id)
    print(queryset)
    
    if queryset != None:
        print("Query", queryset)
        context = {
                "object_list": queryset,
                "title": "list"
            }
    else:
        pass
    return render(request, "post_detail.html", context)

def post_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None,  request.FILES or None, instance=instance)
    print(form)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully Item Updated")
        return HttpResponseRedirect(instance.get_absolute_url())
    
    print("Query", instance)
    context = {
            "instance": instance,
            "title": instance.title,
            "form":form
        }
    return render(request, "post_form.html", context)

def post_delete(request, id=None):
    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, "Successfully Item Updated")

    return redirect("posts:home")



# def listing(request):
#     contact_list = Contact.objects.all()
    
#     return render(request, 'list.html', {'page_obj': page_obj})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}Blog{% endblock head_title %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
        {% include "message_display.html" %}
        <div class="container"> 
            {% block content %}{% endblock content %}
        </div>
        <div id="fb-root"></div>

        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v8.0" nonce="WoXQ6mL1"></script>
        
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

templates/message_display.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/post_detail.html
{% extends  "base.html"%}

{% block head_title %} {{object_list.title}} | {{ block.super }} {% endblock head_title %}

{% block content %}
        <div class="card">
                {% if object_list.image %}
                <img src="{{ object_list.image.url }}" style="max-height: 550px; margin: 0 auto;"  class="card-img-top centered" alt="...">
                {% endif %}
                <div class="card-header" style="border-top: 1px solid rgba(0,0,0,.125);">
                        <div class="row">
                                <div class="col">
                                        {% if object_list.user %}
                                        <small><strong>Author : {{object_list.user}}</strong></small>
                                        {% endif %}
                                </div>
                                <div class="col text-right">
                                        <small>{{object_list.timestamp}}</small>
                                </div>
                        </div>
                </div>
                <div class="card-body">       
                        <h5 class="card-title">{{object_list.title}}</h5>
                        <p class="card-text">{{object_list.content|linebreaks}}</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
                <div class="fb-comments" data-numposts="5" data-width=""></div>
        </div>
{% endblock content %}

templates/post_form.html
{% extends  "base.html"%}

{% block head_title %} {{instance.title}} || {{ block.super }} {% endblock head_title %}

{% block content %}
        <h1>Form</h1>
        <form method="POST" action="" enctype="multipart/form-data">
            <div class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Create Post" />
            </div>
        </form>
{% endblock content %}

templates/post_list.html
{% extends  "base.html"%}

{% block content %}
<div>
    <form method="GET" action="">
        <input type="text" name="q" placeholder="Search post" value="{{request.GET.q}}"/>
        <input type="submit" value="Search" />
    </form>
</div>
<div class="row row-cols-1 row-cols-md-3">
    
    {% for object in object_list%}
        {% comment %}{% url "posts:detail" id=object.id  %}
        <a href='{% url "post:detail" id=object.id %}'><h1>{{object.title}}</h1></a>
        <a href='{{ object.get_absolute_url }}'><h1>{{object.title}}</h1></a>
        <h4>{{object.content}}</h4>{% endcomment %}

        <div class="col mb-4">
            <div class="card">
                {% if object.image  %}
                <img src="{{ object.image.url }}" class="card-img-top" style="height: 200px;" alt="...">
                {%endif%}
                <div class="card-header" style="border-top: 1px solid rgba(0,0,0,.125);">
                    <div class="row">
                        <div class="col">
                        {% if object.user %}
                        <small><strong>Author : {{object.user}}</strong></small>
                        {% endif %}
                        </div>
                        <div class="col text-right">
                            <small>{{object.timestamp}}</small>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    
                <h5 class="card-title">{{object.title}}</h5>
                <p class="card-text">{{object.content|linebreaks|truncatechars:30}}</p>
                <a href="{{ object.get_absolute_url }}" class="btn btn-primary">View</a>
                <a href="{{ object.get_update_url }}" class="btn btn-primary">Update</a>
            </div>
            </div>
        </div>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ object_list.previous_page_number }}{%if request.GET.q%}&q={{request.GET.q}}{%endif%}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>
    
            {% if object_list.has_next %}
                <a href="?page={{ object_list.next_page_number }}">next</a>
                <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock content %}